language: julia
julia:
  - 0.4
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("ControlSystems")'
    - julia -e 'Pkg.clone("https://github.com/tbreloff/VisualRegressionTests.jl.git");'
    - julia -e 'Pkg.clone("https://github.com/JuliaControl/ControlExamplePlots.jl.git");'
    - julia -e 'ENV["PYTHON"]=""'
    - julia -e 'Pkg.add("PyPlot")'
    - julia -e 'Pkg.build("PyCall")'
    - julia -e 'Pkg.test("ControlSystems"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("ControlSystems")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    - julia -e 'Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl")'
    - julia -e 'cd(Pkg.dir("ControlSystems")); include(joinpath("docs", "make.jl"))'
